#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYbcHfao4PRsh83vbqyzRoeIQ8454tWL6SSwzePRThNc4GiVa5BBwezq6F6Rtfg0/tfwAWUJ8AmwvLeqyKXwwtKU6R5uj4DWa9i0dhIpb9q9nZDxZSsX1kYCju8MbEjb+om3IQ8XME/yevvRh1z0POV4iWEOmehNtTu0rIEbTQ9dYZMroijYvYBxC11o05oH82l7oNdiBZ3cIkPNoNLI7jywRQ/8QKuXEW5jyRsnTvDi7tJXe8X8Ezlj7ZGf10KkIYl9x6dh7w4UcIIWA2+t5HJlmxO1VuSfqRMA2xd4565ht+3Jeue9Yjm8XoNTokco4XLEkk4zGvWtNy8JOBBuYb najah@najah-rmd
